services:
  db:
    image: postgis/postgis
    container_name: datacatalog_db
    restart: always
    environment:
      POSTGRES_USER: dc_user
      POSTGRES_PASSWORD: dc_password
      POSTGRES_DB: datacatalog_db
    ports:
      - "5434:5432"

