"""migration

Revision ID: 09d4c2c9cf75
Revises: f3a87db4583c
Create Date: 2025-04-03 14:47:24.408987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d4c2c9cf75'
down_revision: Union[str, None] = 'f3a87db4583c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codeexamples', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('codeexamples', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codeexamples', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('codeexamples', 'title')
    # ### end Alembic commands ###
