"""empty message

Revision ID: 542679f914a2
Revises: 502b9c4f9683
Create Date: 2025-05-09 13:30:48.097908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '542679f914a2'
down_revision: Union[str, None] = '502b9c4f9683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resources', 'license_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resources', 'license_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
