"""empty message

Revision ID: 85585c7481a4
Revises: 8e882bba4ea4
Create Date: 2025-05-09 10:04:13.532329

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85585c7481a4"
down_revision: Union[str, None] = "8e882bba4ea4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("resources", sa.Column("data_hub_url", sa.String(), nullable=True))
    op.add_column(
        "resources", sa.Column("research_paper_url", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resources", "research_paper_url")
    op.drop_column("resources", "data_hub_url")
    # ### end Alembic commands ###
