"""empty message

Revision ID: 8e882bba4ea4
Revises: 0285dbd55d4d
Create Date: 2025-05-08 14:32:01.811225

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e882bba4ea4"
down_revision: Union[str, None] = "0285dbd55d4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("examples", sa.Column("title", sa.String(), nullable=False))
    op.alter_column("examples", "type", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "examples", "example_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("examples", "resource_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("examples", "resource_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "examples", "example_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("examples", "type", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("examples", "title")
    # ### end Alembic commands ###
