"""migration

Revision ID: ca00ef6f04a5
Revises: 09d4c2c9cf75
Create Date: 2025-04-04 10:01:29.503210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca00ef6f04a5'
down_revision: Union[str, None] = '09d4c2c9cf75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('source', sa.String(), nullable=True))
    op.drop_column('code', 'codetext')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('codetext', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('code', 'source')
    # ### end Alembic commands ###
