"""empty message

Revision ID: f5f39a679440
Revises: 5992f61f9fb2
Create Date: 2025-06-03 09:44:07.916449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5f39a679440"
down_revision: Union[str, None] = "5992f61f9fb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_resource_category_resource_id_resources",
        "resource_category",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_resource_category_resource_id_resources"),
        "resource_category",
        "resources",
        ["resource_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_spatial_extent_geometry_relation_spatial_extent_id_s_cc8d",
        "spatial_extent_geometry_relation",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_spatial_extent_geometry_relation_geometry_id_geometries",
        "spatial_extent_geometry_relation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_spatial_extent_geometry_relation_spatial_extent_id_spatial_extents"),
        "spatial_extent_geometry_relation",
        "spatial_extents",
        ["spatial_extent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_spatial_extent_geometry_relation_geometry_id_geometries"),
        "spatial_extent_geometry_relation",
        "geometries",
        ["geometry_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_spatial_extents_resource_id_resources",
        "spatial_extents",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_spatial_extents_resource_id_resources"),
        "spatial_extents",
        "resources",
        ["resource_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_spatial_extents_resource_id_resources"),
        "spatial_extents",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_spatial_extents_resource_id_resources",
        "spatial_extents",
        "resources",
        ["resource_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_spatial_extent_geometry_relation_geometry_id_geometries"),
        "spatial_extent_geometry_relation",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_spatial_extent_geometry_relation_spatial_extent_id_spatial_extents"),
        "spatial_extent_geometry_relation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_spatial_extent_geometry_relation_geometry_id_geometries",
        "spatial_extent_geometry_relation",
        "geometries",
        ["geometry_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_spatial_extent_geometry_relation_spatial_extent_id_s_cc8d",
        "spatial_extent_geometry_relation",
        "spatial_extents",
        ["spatial_extent_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_resource_category_resource_id_resources"),
        "resource_category",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_resource_category_resource_id_resources",
        "resource_category",
        "resources",
        ["resource_id"],
        ["id"],
    )
    # ### end Alembic commands ###
