"""empty message

Revision ID: ffe076a00ebf
Revises: 04ba5a452b09
Create Date: 2025-05-12 15:14:17.680067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe076a00ebf'
down_revision: Union[str, None] = '04ba5a452b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('data_hub_url', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('research_paper_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'research_paper_url')
    op.drop_column('resources', 'data_hub_url')
    # ### end Alembic commands ###
